name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'back/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      working-directory: back
      run: npm ci
    - name: Build
      working-directory: back
      run: npm run build
    - name: Test
      working-directory: back
      run: npm test
